apiVersion: apps/v1
kind: Deployment
metadata:
  name:  weather-api
spec:
  selector:
    matchLabels:
      app: weather-api
  replicas: 2
  template:
    metadata:
      labels:
        app:  weather-api
    spec:
      containers:
        - name: weather-api
          image: adchouaib/weather-api:latest
          ports: 
            - containerPort: 8080